# Generated by Django 3.0.14 on 2023-12-31 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(blank=True, max_length=100)),
                ('lastName', models.CharField(blank=True, max_length=100)),
                ('profile_path', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(blank=True, max_length=100)),
                ('lastName', models.CharField(blank=True, max_length=100)),
                ('profile_path', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movieId', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=500)),
                ('releaseYear', models.CharField(blank=True, max_length=5, null=True)),
                ('duration', models.CharField(blank=True, max_length=10, null=True)),
                ('trailerUrl', models.CharField(blank=True, max_length=100, null=True)),
                ('imgUrl', models.CharField(max_length=100)),
                ('tagLine', models.CharField(blank=True, max_length=500, null=True)),
                ('overview', models.CharField(blank=True, max_length=1000, null=True)),
                ('country', models.CharField(max_length=50)),
                ('originalLanguage', models.CharField(max_length=100)),
                ('actors', models.ManyToManyField(blank=True, null=True, to='base.Actor')),
                ('directors', models.ManyToManyField(blank=True, null=True, to='base.Director')),
                ('genres', models.ManyToManyField(blank=True, null=True, to='base.Genre')),
            ],
            options={
                'db_table': 'movie',
            },
        ),
    ]
